---
- name: install freeradius
  package:
    name: "{{ freeradius_packages }}"
    state: present

- name: enable and start freeradius
  service:
    name: "{{ freeradius_service_name }}"
    enabled: yes
    state: started
